targets:
  $default:
    builders:
      json_serializable:
        options:
          # Configurazioni per la serializzazione JSON
          explicit_to_json: true
          include_if_null: false
        generate_for:
          - lib/models/**.dart
          - lib/handlers/**.dart
