name: golem_backend
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  aws_dynamodb_api: null
  aws_lambda_dart_runtime: ^1.1.0
  shelf:
  shelf_router:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner:
  lints:
  json_serializable: ^6.7.1
